#!/usr/bin/env bash

set -uo pipefail

SCRIPT_NAME="phase1-wazuh-alert-triage"
TIMESTAMP="$(date '+%Y%m%d-%H%M%S')"

REPO_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
REPORT_DIR="${REPO_DIR}/reports"
EVIDENCE_DIR="${REPO_DIR}/evidence/${SCRIPT_NAME}-${TIMESTAMP}"

REPORT_FILE="${REPORT_DIR}/${SCRIPT_NAME}-${TIMESTAMP}.txt"

mkdir -p "$REPORT_DIR" "$EVIDENCE_DIR"

PASS=0
WARN=0
FAIL=0

log() {
    printf '%s\n' "$*" | tee -a "$REPORT_FILE"
}

pass() {
    PASS=$((PASS + 1))
    log "[PASS] $*"
}

warn() {
    WARN=$((WARN + 1))
    log "[WARN] $*"
}

fail() {
    FAIL=$((FAIL + 1))
    log "[FAIL] $*"
}

section() {
    log ""
    log "================================================================"
    log "$*"
    log "================================================================"
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

section "PHASE 1 LAB 3.1 — WAZUH ALERT TRIAGE & INCIDENT SCOPING"

log "Started:       $(date -Is)"
log "Repository:    $REPO_DIR"
log "Evidence:      $EVIDENCE_DIR"
log "Report:        $REPORT_FILE"
log "Host:          $(hostname)"
log "Kernel:        $(uname -sr)"
log ""

section "1. ENVIRONMENT VALIDATION"

if command_exists docker; then
    pass "Docker is available"
else
    fail "Docker command is unavailable"
fi

if docker info >/dev/null 2>&1; then
    pass "Docker daemon is accessible"
else
    fail "Docker daemon is not accessible"
fi

MANAGER_CONTAINER="$(docker ps --format '{{.Names}}' | grep -E 'wazuh\.manager|wazuh-manager' | head -n1 || true)"

if [[ -n "$MANAGER_CONTAINER" ]]; then
    pass "Wazuh manager container detected: $MANAGER_CONTAINER"
else
    fail "Wazuh manager container was not detected"
fi

ALERT_FILE="/var/ossec/logs/alerts/alerts.json"

if [[ -n "$MANAGER_CONTAINER" ]] && \
   docker exec "$MANAGER_CONTAINER" test -f "$ALERT_FILE" >/dev/null 2>&1; then
    pass "Manager alerts.json is available"
else
    fail "Manager alerts.json is unavailable"
fi

section "2. CAPTURE CURRENT MANAGER ALERT DATA"

if [[ -n "$MANAGER_CONTAINER" ]]; then
    docker exec "$MANAGER_CONTAINER" cat "$ALERT_FILE" \
        > "${EVIDENCE_DIR}/alerts-full.jsonl" 2>/dev/null

    if [[ -s "${EVIDENCE_DIR}/alerts-full.jsonl" ]]; then
        ALERT_COUNT="$(wc -l < "${EVIDENCE_DIR}/alerts-full.jsonl")"
        pass "Captured manager alert stream: ${ALERT_COUNT} records"
    else
        fail "Manager alert stream capture is empty"
    fi
fi

section "3. IDENTIFY LAB 2.1 VALIDATION EVIDENCE"

LAB21_REPORT="$(find "$REPORT_DIR" -maxdepth 1 -type f \
    -name 'phase1-wazuh-manager-alert-validation-*.txt' \
    -printf '%T@ %p\n' 2>/dev/null | sort -nr | head -n1 | cut -d' ' -f2- || true)"

if [[ -n "$LAB21_REPORT" && -f "$LAB21_REPORT" ]]; then
    pass "Latest Lab 2.1 report found: $(basename "$LAB21_REPORT")"

    cp "$LAB21_REPORT" "${EVIDENCE_DIR}/lab2.1-report.txt"

    {
        echo "Lab 2.1 report:"
        echo "$LAB21_REPORT"
        echo
        echo "Relevant timestamps discovered from report:"
        grep -Ei \
            'started:|completed:|timestamp|baseline|post|validation|alert|sudo|5501|5502|5402' \
            "$LAB21_REPORT" || true
    } > "${EVIDENCE_DIR}/lab2.1-context.txt"

else
    warn "No Lab 2.1 manager-alert-validation report was found"
fi

section "4. DETERMINE ALERT TIME RANGE"

if [[ -s "${EVIDENCE_DIR}/alerts-full.jsonl" ]]; then

    if command_exists jq; then

        jq -r '
            select(.timestamp != null) |
            [.timestamp, (.rule.id // ""), (.rule.level // ""), (.agent.id // ""), (.agent.name // "")] |
            @tsv
        ' "${EVIDENCE_DIR}/alerts-full.jsonl" \
        > "${EVIDENCE_DIR}/alert-timeline.tsv" 2>/dev/null || true

        if [[ -s "${EVIDENCE_DIR}/alert-timeline.tsv" ]]; then
            pass "Structured alert timeline generated"

            {
                echo "Earliest alert:"
                head -n1 "${EVIDENCE_DIR}/alert-timeline.tsv"
                echo
                echo "Latest alert:"
                tail -n1 "${EVIDENCE_DIR}/alert-timeline.tsv"
            } > "${EVIDENCE_DIR}/alert-time-range.txt"
        else
            warn "Unable to generate structured alert timeline"
        fi

    else
        warn "jq is unavailable; JSON analysis will be limited"
    fi
fi

section "5. TARGETED LAB 2.1 ALERT EXTRACTION"

# Lab 2.1 documented exactly three controlled Wazuh alerts:
# 2026-09-24T06:47:09.509+0000  rule 5402
# 2026-09-24T06:47:09.509+0000  rule 5502
# 2026-09-24T06:47:09.510+0000  rule 5501
#
# The earlier 06:47:07 events were generated by the sudo invocation
# used to launch the validation script. They are retained as pre-test
# context and are not classified as controlled test alerts.

LAB21_CONTROLLED_TS_1="2026-09-24T06:47:09.509+0000"
LAB21_CONTROLLED_TS_2="2026-09-24T06:47:09.510+0000"

if [[ -s "${EVIDENCE_DIR}/alerts-full.jsonl" ]] && command_exists jq; then

    jq -c \
        --arg ts1 "$LAB21_CONTROLLED_TS_1" \
        --arg ts2 "$LAB21_CONTROLLED_TS_2" '
        select(
            (.timestamp // "") == $ts1 or
            (.timestamp // "") == $ts2
        )
        ' "${EVIDENCE_DIR}/alerts-full.jsonl" \
        > "${EVIDENCE_DIR}/lab21-window-all.jsonl" 2>/dev/null || true

    WINDOW_COUNT="$(wc -l < "${EVIDENCE_DIR}/lab21-window-all.jsonl" 2>/dev/null || echo 0)"

    if [[ "$WINDOW_COUNT" -gt 0 ]]; then
        pass "Captured ${WINDOW_COUNT} alerts at the documented Lab 2.1 controlled timestamps"
    else
        warn "No alerts found at the documented Lab 2.1 controlled timestamps"
    fi

    jq -c '
        select(
            (.rule.id == "5402") or
            (.rule.id == "5501") or
            (.rule.id == "5502")
        )
        ' "${EVIDENCE_DIR}/lab21-window-all.jsonl" \
        > "${EVIDENCE_DIR}/controlled-alerts.jsonl" 2>/dev/null || true

    CONTROLLED_COUNT="$(wc -l < "${EVIDENCE_DIR}/controlled-alerts.jsonl" 2>/dev/null || echo 0)"

    if [[ "$CONTROLLED_COUNT" -eq 3 ]]; then
        pass "Exactly 3 controlled Lab 2.1 alerts isolated"
    elif [[ "$CONTROLLED_COUNT" -gt 0 ]]; then
        warn "Found ${CONTROLLED_COUNT} controlled-rule alerts at the documented timestamps; expected 3"
    else
        warn "No controlled Lab 2.1 alerts isolated"
    fi

    jq -r '
        [
            .timestamp,
            (.agent.id // ""),
            (.agent.name // ""),
            (.rule.id // ""),
            (.rule.level // ""),
            (.rule.description // ""),
            (.decoder.name // ""),
            (.location // "")
        ] | @tsv
    ' "${EVIDENCE_DIR}/controlled-alerts.jsonl" \
        > "${EVIDENCE_DIR}/controlled-alert-summary.tsv" 2>/dev/null || true

    jq -r '
        [
            .timestamp,
            (.agent.id // ""),
            (.agent.name // ""),
            (.rule.id // ""),
            (.rule.level // ""),
            (.rule.description // ""),
            (.decoder.name // ""),
            (.location // "")
        ] | @tsv
    ' "${EVIDENCE_DIR}/lab21-window-all.jsonl" \
        > "${EVIDENCE_DIR}/lab21-window-timeline.tsv" 2>/dev/null || true

else
    warn "Manager alert data or jq unavailable for controlled-alert extraction"
fi

# Preserve the separate Rule 80710 investigation.
if [[ -s "${EVIDENCE_DIR}/alerts-full.jsonl" ]] && command_exists jq; then

    jq -c '
        select(.rule.id == "80710")
    ' "${EVIDENCE_DIR}/alerts-full.jsonl" \
        > "${EVIDENCE_DIR}/rule-80710-alerts.jsonl" 2>/dev/null || true

    PROMISC_COUNT="$(wc -l < "${EVIDENCE_DIR}/rule-80710-alerts.jsonl" 2>/dev/null || echo 0)"

    if [[ "$PROMISC_COUNT" -gt 0 ]]; then
        warn "Rule 80710 appears ${PROMISC_COUNT} time(s); separate contextual investigation required"
    else
        pass "Rule 80710 was not present in captured alert data"
    fi
fi

section "6. CONTROLLED ALERT ANALYSIS"

if [[ -s "${EVIDENCE_DIR}/controlled-alerts.jsonl" ]] && command_exists jq; then

    {
        echo "CONTROLLED LAB ALERTS"
        echo "====================="
        echo

        jq -r '
            [
                .timestamp,
                (.rule.id // ""),
                ("level=" + ((.rule.level // 0)|tostring)),
                (.rule.description // ""),
                ("agent=" + (.agent.name // "")),
                ("decoder=" + (.decoder.name // "")),
                ("location=" + (.location // ""))
            ] | @tsv
        ' "${EVIDENCE_DIR}/controlled-alerts.jsonl"
    } > "${EVIDENCE_DIR}/controlled-alert-analysis.txt"

    cat "${EVIDENCE_DIR}/controlled-alert-analysis.txt" >> "$REPORT_FILE"

    pass "Controlled Lab 2.1 alerts documented"
else
    warn "Controlled-alert analysis unavailable"
fi

section "7. RULE 80710 — PROMISCUOUS MODE INVESTIGATION"

if [[ -s "${EVIDENCE_DIR}/rule-80710-alerts.jsonl" ]] && command_exists jq; then

    {
        echo "RULE 80710 ALERT DETAILS"
        echo "========================"
        echo

        jq -r '
            [
                .timestamp,
                (.rule.id // ""),
                (.rule.level // ""),
                (.rule.description // ""),
                (.agent.name // ""),
                (.decoder.name // ""),
                (.location // ""),
                (.full_log // "")
            ] | @tsv
        ' "${EVIDENCE_DIR}/rule-80710-alerts.jsonl"
    } > "${EVIDENCE_DIR}/rule-80710-analysis.tsv"

    cat "${EVIDENCE_DIR}/rule-80710-analysis.tsv" >> "$REPORT_FILE"

    warn "Rule 80710 requires environmental/contextual review; no malicious conclusion is made"
else
    pass "No Rule 80710 evidence requires separate review"
fi

section "8. AUDITD CORRELATION"

if [[ -f /var/log/audit/audit.log ]]; then

    cp /var/log/audit/audit.log \
        "${EVIDENCE_DIR}/audit.log" 2>/dev/null || \
        warn "Could not copy audit.log"

    grep -Ei \
        'sudo|EXECVE|USER_CMD|USER_START|USER_END|PROCTITLE|promisc|ip link|ifconfig' \
        /var/log/audit/audit.log \
        > "${EVIDENCE_DIR}/auditd-relevant-events.txt" 2>/dev/null || true

    if [[ -s "${EVIDENCE_DIR}/auditd-relevant-events.txt" ]]; then
        pass "Relevant Auditd events extracted"
    else
        warn "No matching Auditd correlation events were found"
    fi

else
    warn "/var/log/audit/audit.log is unavailable"
fi

section "9. SUDO / PAM CORRELATION"

if [[ -f /var/log/auth.log ]]; then

    grep -Ei \
        'sudo|session opened|session closed|authentication' \
        /var/log/auth.log \
        > "${EVIDENCE_DIR}/auth-relevant-events.txt" 2>/dev/null || true

    if [[ -s "${EVIDENCE_DIR}/auth-relevant-events.txt" ]]; then
        pass "Authentication/Sudo events extracted from auth.log"
    else
        warn "No matching authentication events found in auth.log"
    fi
else
    warn "/var/log/auth.log is unavailable"
fi

if command_exists journalctl; then

    journalctl --since "24 hours ago" --no-pager \
        | grep -Ei 'sudo|pam_unix|session opened|session closed' \
        > "${EVIDENCE_DIR}/journal-auth-events.txt" 2>/dev/null || true

    if [[ -s "${EVIDENCE_DIR}/journal-auth-events.txt" ]]; then
        pass "Recent journal authentication events extracted"
    else
        warn "No recent matching journal authentication events found"
    fi
fi

section "10. AGENT / HOST CORRELATION"

if [[ -s "${EVIDENCE_DIR}/controlled-alerts.jsonl" ]] && command_exists jq; then

    jq -r '
        [
            (.agent.id // ""),
            (.agent.name // ""),
            (.timestamp // ""),
            (.rule.id // ""),
            (.rule.level // "")
        ] | @tsv
    ' "${EVIDENCE_DIR}/controlled-alerts.jsonl" \
    | sort -u > "${EVIDENCE_DIR}/controlled-agent-correlation.tsv"

    if [[ -s "${EVIDENCE_DIR}/controlled-agent-correlation.tsv" ]]; then
        pass "Controlled-alert agent correlation generated"
    else
        warn "Controlled-alert agent correlation is empty"
    fi
fi

section "11. ALERT CATEGORIZATION"

cat > "${EVIDENCE_DIR}/alert-categorization.txt" <<'CATEGORIES'
SOC TRIAGE CATEGORIZATION

CATEGORY 1 — EXPECTED / CONTROLLED LAB ACTIVITY
Rules 5402, 5501 and 5502 are associated with the controlled Lab 2.1
validation activity previously performed on the endpoint. These alerts
should be treated as expected test telemetry when their timestamps,
agent identity and surrounding evidence match the documented test window.

CATEGORY 2 — ENVIRONMENTAL / SYSTEM ACTIVITY
Alerts generated by package management, SCA, Wazuh startup, routine
system activity, or other expected host operations require contextual
review before being interpreted as security incidents.

CATEGORY 3 — REQUIRES INVESTIGATION
Rule 80710 (promiscuous mode) is a higher-severity signal and must not
automatically be classified as malicious. Its meaning depends on the
host's expected networking configuration, process activity, user action,
and Auditd evidence.

NO COMPROMISE CONCLUSION
This lab does not establish compromise merely from the presence of an
alert. Conclusions must be based on correlated evidence and the known
controlled test window.
CATEGORIES

cat "${EVIDENCE_DIR}/alert-categorization.txt" >> "$REPORT_FILE"

pass "Alert categorization framework generated"

section "12. MITRE ATT&CK CONTEXT"

cat > "${EVIDENCE_DIR}/mitre-context.txt" <<'MITRE'
MITRE ATT&CK CONTEXT

Rule 5402:
Potential ATT&CK mapping: T1548.003 — Abuse Elevation Control Mechanism:
Sudo and Sudo Caching.

This mapping is contextual only. In the controlled Lab 2.1 scenario,
the sudo activity was intentionally generated for telemetry validation.
It is not evidence of malicious privilege escalation by itself.

Rules 5501 and 5502:
PAM session-open/session-close alerts provide authentication/session
context. No ATT&CK technique is asserted solely from these alerts.

Rule 80710:
No ATT&CK technique is asserted solely from the promiscuous-mode alert.
Additional process, network-interface and Auditd evidence is required.
MITRE

cat "${EVIDENCE_DIR}/mitre-context.txt" >> "$REPORT_FILE"

pass "MITRE ATT&CK context documented without asserting unsupported compromise"

section "13. ANALYST TIMELINE"

if [[ -s "${EVIDENCE_DIR}/controlled-alert-summary.tsv" ]]; then

    {
        echo "TIMESTAMP	RULE	LEVEL	DESCRIPTION	AGENT	DECODER	LOCATION"
        cat "${EVIDENCE_DIR}/controlled-alert-summary.tsv"
    } > "${EVIDENCE_DIR}/analyst-timeline.tsv"

    pass "Controlled-event analyst timeline generated"
else
    warn "Analyst timeline could not be generated"
fi

section "14. EVIDENCE MANIFEST"

find "$EVIDENCE_DIR" -maxdepth 1 -type f -printf '%f\n' \
    | sort > "${EVIDENCE_DIR}/evidence-manifest.txt"

MANIFEST_COUNT="$(wc -l < "${EVIDENCE_DIR}/evidence-manifest.txt")"

log "Evidence files generated: $MANIFEST_COUNT"
pass "Evidence manifest generated"

section "15. FINAL TRIAGE ASSESSMENT"

log ""
log "Controlled Lab 2.1 alerts:"
log "  5402 — Successful sudo to ROOT"
log "  5501 — PAM session opened"
log "  5502 — PAM session closed"
log ""
log "Assessment:"
log "  The above rules are expected security telemetry when correlated"
log "  with the documented controlled validation activity."
log ""
log "High-severity contextual signal:"
log "  Rule 80710 — Auditd: Device enables promiscuous mode"
log ""
log "Rule 80710 disposition:"
log "  Requires contextual investigation."
log "  Presence alone does NOT establish malicious activity."
log ""
log "Compromise determination:"
log "  No compromise is established by this triage procedure alone."
log "  Conclusions require correlated endpoint, authentication, Auditd,"
log "  process and network evidence."

section "16. VALIDATION SUMMARY"

log "PASS: $PASS"
log "WARN: $WARN"
log "FAIL: $FAIL"
log ""
log "Completed: $(date -Is)"
log ""
log "Report:   $REPORT_FILE"
log "Evidence: $EVIDENCE_DIR"

if [[ "$FAIL" -eq 0 ]]; then
    log ""
    log "RESULT: TRIAGE COLLECTION COMPLETED WITHOUT HARD FAILURES"
else
    log ""
    log "RESULT: TRIAGE COLLECTION COMPLETED WITH FAILURES"
fi

exit 0
