name: Actions Startup Probe

on:
  pull_request:
  push:

jobs:
  probe:
    name: actions-probe
    runs-on: ubuntu-latest
    steps:
      - name: Probe
        run: echo "GitHub Actions startup probe passed."
